frr version 8.4_git
frr defaults traditional
hostname r1
log syslog informational
service integrated-vtysh-config
ipv6 forwarding
!
interface lo
 ipv6 address 2001:db8:1::1/128
 ipv6 router isis CORE
 isis passive
!
interface eth1
 ipv6 address 2001:db8:12::1/64
 ipv6 router isis CORE
 isis network point-to-point
 isis hello-interval 3
!
router isis CORE
 net 49.0001.0000.0000.0001.00
 is-type level-2-only
 metric-style wide
 topology ipv6-unicast
 redistribute ipv6 connected level-2
!
line vty
!
