frr version 8.4_git
frr defaults traditional
hostname r1
log syslog informational
service integrated-vtysh-config
ipv6 forwarding
!
vrf TENANT_A
 vni 101
exit-vrf
!
interface lo
 ipv6 address 2001:db8:1::1/128
 ipv6 router isis CORE
 isis passive
!
interface lo:1
 vrf TENANT_A
 ip address 192.168.1.1/32
 ipv6 address 2001:db8:dead::1/128
!
interface eth1
 ipv6 address 2001:db8:12::1/64
 ipv6 router isis CORE
 isis network point-to-point
 isis hello-interval 3
!
router isis CORE
 net 49.0001.0000.0000.0001.00
 is-type level-2-only
 metric-style wide
 topology ipv6-unicast
 redistribute ipv6 connected level-2
 segment-routing srv6
  locator LOC1
 exit
!
segment-routing
 srv6
  locators
   locator LOC1
    prefix 2001:db8:1::/64
   exit
  exit
 exit
!
router bgp 65001
 bgp router-id 1.1.1.1
 no bgp default ipv4-unicast
 neighbor 2001:db8:2::2 remote-as 65002
 neighbor 2001:db8:2::2 update-source lo
 !
 address-family ipv6 vpn
  neighbor 2001:db8:2::2 activate
  segment-routing srv6
   locator LOC1
  exit
 exit-address-family
!
router bgp 65001 vrf TENANT_A
 bgp router-id 1.1.1.1
 !
 address-family ipv4 unicast
  redistribute connected
  segment-routing srv6
   locator LOC1
   auto-sid
  exit
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute connected
  segment-routing srv6
   locator LOC1
   auto-sid
  exit
 exit-address-family
!
line vty
!
